---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog2image
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: datadog2image
  template:
    metadata:
      labels:
        app: datadog2image
    spec:
      containers:
      - image: n0madic/datadog2image
        imagePullPolicy: Always
        name: datadog2image
        args: ["-http", ":8000"]
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 30
        env:
        - name: TZ
          value: "Europe/Kiev"
        resources:
          requests:
            memory: "768Mi"
            cpu: "350m"
          limits:
            memory: "4Gi"
            cpu: "1"
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: datadog2image
spec:
  type: ClusterIP
  selector:
    app: datadog2image
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: datadog2image
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: datadog2image.service
    http:
      paths:
      - path: /
        backend:
          serviceName: datadog2image
          servicePort: 80
